import { Profile, TrustedContact, CommunityReport, SafetyJourney, WalkTogetherRequest } from '../types/database';
import { RouteOption } from '../types/safety';

export const SEEDED_PROFILES: Profile[] = [
  {
    id: 'user-alex-rivera',
    email: 'alex.rivera@university.edu',
    full_name: 'Alex Rivera',
    phone: '+1 (555) 234-5678',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    emergency_pin: '1234',
    safe_phrase: 'Midnight Horizon',
    duress_code: '9999',
    blood_group: 'O+',
    medical_notes: 'Mild asthma, carries inhaler',
    default_grace_period_seconds: 60,
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'user-sarah-chen',
    email: 'sarah.chen@cityhospital.org',
    full_name: 'Dr. Sarah Chen',
    phone: '+1 (555) 876-5432',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    emergency_pin: '4321',
    safe_phrase: 'Golden Gate',
    duress_code: '8888',
    blood_group: 'A+',
    medical_notes: 'No known allergies',
    default_grace_period_seconds: 90,
    created_at: '2026-02-10T14:30:00Z',
  },
  {
    id: 'user-marcus-vance',
    email: 'marcus.vance@techcorp.io',
    full_name: 'Marcus Vance',
    phone: '+1 (555) 912-3456',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    emergency_pin: '7777',
    safe_phrase: 'Silver Cloud',
    duress_code: '0000',
    blood_group: 'B+',
    medical_notes: 'Penicillin allergy',
    default_grace_period_seconds: 60,
    created_at: '2026-03-01T09:15:00Z',
  },
];

export const SEEDED_TRUSTED_CONTACTS: Record<string, TrustedContact[]> = {
  'user-alex-rivera': [
    {
      id: 'contact-1',
      user_id: 'user-alex-rivera',
      name: 'Elena Rivera (Mother)',
      relationship: 'Mother',
      phone: '+1 (555) 301-8899',
      email: 'elena.rivera@family.com',
      alert_priority: 1,
      notify_on_start: true,
      notify_on_check_missed: true,
      notify_on_sos: true,
      created_at: '2026-01-16T10:00:00Z',
    },
    {
      id: 'contact-2',
      user_id: 'user-alex-rivera',
      name: 'Jordan Miller (Roommate)',
      relationship: 'Roommate',
      phone: '+1 (555) 443-1289',
      email: 'jmiller@university.edu',
      alert_priority: 1,
      notify_on_start: true,
      notify_on_check_missed: true,
      notify_on_sos: true,
      created_at: '2026-01-20T12:00:00Z',
    },
    {
      id: 'contact-3',
      user_id: 'user-alex-rivera',
      name: 'Campus Campus Safety Dispatch',
      relationship: 'Campus Security',
      phone: '+1 (555) 999-0011',
      email: 'dispatch@campus-safety.edu',
      alert_priority: 2,
      notify_on_start: false,
      notify_on_check_missed: false,
      notify_on_sos: true,
      created_at: '2026-02-01T08:00:00Z',
    },
  ],
  'user-sarah-chen': [
    {
      id: 'contact-4',
      user_id: 'user-sarah-chen',
      name: 'David Chen (Spouse)',
      relationship: 'Spouse',
      phone: '+1 (555) 782-9901',
      email: 'david.chen@gmail.com',
      alert_priority: 1,
      notify_on_start: true,
      notify_on_check_missed: true,
      notify_on_sos: true,
      created_at: '2026-02-11T09:00:00Z',
    },
  ],
  'user-marcus-vance': [
    {
      id: 'contact-5',
      user_id: 'user-marcus-vance',
      name: 'Chloe Vance (Sister)',
      relationship: 'Sister',
      phone: '+1 (555) 662-8812',
      email: 'chloe.vance@yahoo.com',
      alert_priority: 1,
      notify_on_start: true,
      notify_on_check_missed: true,
      notify_on_sos: true,
      created_at: '2026-03-02T11:00:00Z',
    },
  ],
};

export const SEEDED_COMMUNITY_REPORTS: CommunityReport[] = [
  {
    id: 'rep-1',
    category: 'poor_lighting',
    severity: 'medium',
    title: 'Broken Street Lamps near Park West Entrance',
    description: 'Entire row of 4 street lamps are non-functional. The sidewalk is completely dark after 8:00 PM.',
    lat: 37.7762,
    lng: -122.4215,
    location_name: 'Park West Blvd & 8th St',
    upvotes: 18,
    status: 'verified',
    created_at: '2026-08-18T21:40:00Z',
  },
  {
    id: 'rep-2',
    category: 'harassment',
    severity: 'high',
    title: 'Verbal Harassment by Group near Underpass',
    description: '2 pedestrians reported aggressive catcalling and following near the pedestrian underpass.',
    lat: 37.7735,
    lng: -122.4182,
    location_name: 'Central Underpass Walkway',
    upvotes: 27,
    status: 'verified',
    created_at: '2026-08-19T01:15:00Z',
  },
  {
    id: 'rep-3',
    category: 'infrastructure_hazard',
    severity: 'low',
    title: 'Sidewalk Construction with Narrow Walkway',
    description: 'Construction fencing forces pedestrians into a narrow blind spot. Moderate trip hazard.',
    lat: 37.7791,
    lng: -122.4148,
    location_name: 'Market St & 6th Ave',
    upvotes: 7,
    status: 'verified',
    created_at: '2026-08-17T15:20:00Z',
  },
  {
    id: 'rep-4',
    category: 'isolated_area',
    severity: 'high',
    title: 'Dead Zone behind Industrial Complex',
    description: 'Very little foot traffic after 9 PM. No active storefronts or security presence for 4 blocks.',
    lat: 37.7712,
    lng: -122.4115,
    location_name: 'Warehouse Alley & 4th',
    upvotes: 34,
    status: 'verified',
    created_at: '2026-08-16T23:05:00Z',
  },
  {
    id: 'rep-5',
    category: 'suspicious_activity',
    severity: 'medium',
    title: 'Unattended Vehicle Loitering at Bus Stop',
    description: 'Vehicle idling without headlights near the transit shelter for multiple hours.',
    lat: 37.7812,
    lng: -122.4239,
    location_name: 'Pine St & Van Ness',
    upvotes: 12,
    status: 'pending',
    created_at: '2026-08-19T04:22:00Z',
  },
];

export const SAMPLE_ROUTES: RouteOption[] = [
  {
    id: 'route-safest',
    name: 'Avenue of the Arts & Civic Plaza',
    type: 'safest',
    tag: 'Recommended - Safest',
    distanceKm: 2.1,
    durationMins: 24,
    safetyScore: 92,
    recommendationReason: 'Continuous street lighting, 6 open late-night commercial venues, 2 active security kiosks, and 0 recent incident reports.',
    factors: {
      lighting: 96,
      footTraffic: 88,
      emergencyProximity: 94,
      incidentDensityScore: 92,
      infrastructureScore: 90,
      isolationRisk: 12,
    },
    keyHighlights: [
      'Continuous LED street lighting along entire path',
      'Passes 24/7 Pharmacy & Open Cafe',
      'Within 300m of Central Police Substation',
      'Active pedestrian foot traffic until midnight',
    ],
    riskWarnings: [
      '+3 mins longer than direct alley route',
    ],
    coordinates: [
      [-122.4225, 37.7805], // Library
      [-122.4208, 37.7802],
      [-122.4190, 37.7791],
      [-122.4172, 37.7778],
      [-122.4155, 37.7765],
      [-122.4140, 37.7750],
      [-122.4128, 37.7738], // Home
    ],
    segments: [
      {
        id: 'seg-1',
        route_id: 'route-safest',
        segment_index: 0,
        start_lat: 37.7805,
        start_lng: -122.4225,
        end_lat: 37.7791,
        end_lng: -122.4190,
        risk_level: 'low',
        lighting_score: 98,
        incident_count: 0,
        nearby_amenities_count: 5,
        notes: 'University Campus Perimeter - High security presence',
      },
      {
        id: 'seg-2',
        route_id: 'route-safest',
        segment_index: 1,
        start_lat: 37.7791,
        start_lng: -122.4190,
        end_lat: 37.7765,
        end_lng: -122.4155,
        risk_level: 'low',
        lighting_score: 95,
        incident_count: 0,
        nearby_amenities_count: 7,
        notes: 'Civic Plaza - Broad lighted avenues & CCTV coverage',
      },
      {
        id: 'seg-3',
        route_id: 'route-safest',
        segment_index: 2,
        start_lat: 37.7765,
        start_lng: -122.4155,
        end_lat: 37.7738,
        end_lng: -122.4128,
        risk_level: 'low',
        lighting_score: 90,
        incident_count: 0,
        nearby_amenities_count: 4,
        notes: 'Residential Boulevard with active residential lighting',
      },
    ],
  },
  {
    id: 'route-balanced',
    name: 'Market St Transit Corridor',
    type: 'balanced',
    tag: 'Balanced - Fast & Monitored',
    distanceKm: 1.8,
    durationMins: 20,
    safetyScore: 82,
    recommendationReason: 'Good balance of transit hub proximity and travel time. Moderately busy with standard street lights.',
    factors: {
      lighting: 82,
      footTraffic: 84,
      emergencyProximity: 80,
      incidentDensityScore: 80,
      infrastructureScore: 85,
      isolationRisk: 24,
    },
    keyHighlights: [
      'Passes 2 illuminated Metro transit stops',
      'Even sidewalks and standard streetlamps',
      'Short travel duration (20 mins)',
    ],
    riskWarnings: [
      'Minor construction zone with narrow sidewalk near 6th St',
    ],
    coordinates: [
      [-122.4225, 37.7805],
      [-122.4210, 37.7788],
      [-122.4180, 37.7762],
      [-122.4150, 37.7745],
      [-122.4128, 37.7738],
    ],
    segments: [
      {
        id: 'seg-4',
        route_id: 'route-balanced',
        segment_index: 0,
        start_lat: 37.7805,
        start_lng: -122.4225,
        end_lat: 37.7788,
        end_lng: -122.4210,
        risk_level: 'low',
        lighting_score: 85,
        incident_count: 0,
        nearby_amenities_count: 4,
      },
      {
        id: 'seg-5',
        route_id: 'route-balanced',
        segment_index: 1,
        start_lat: 37.7788,
        start_lng: -122.4210,
        end_lat: 37.7745,
        end_lng: -122.4150,
        risk_level: 'medium',
        lighting_score: 75,
        incident_count: 1,
        nearby_amenities_count: 3,
        notes: 'Moderate congestion near subway entrance',
      },
      {
        id: 'seg-6',
        route_id: 'route-balanced',
        segment_index: 2,
        start_lat: 37.7745,
        start_lng: -122.4150,
        end_lat: 37.7738,
        end_lng: -122.4128,
        risk_level: 'low',
        lighting_score: 86,
        incident_count: 0,
        nearby_amenities_count: 3,
      },
    ],
  },
  {
    id: 'route-fastest',
    name: 'Industrial Cut-through Alley',
    type: 'fastest',
    tag: 'Fastest - High Risk',
    distanceKm: 1.4,
    durationMins: 16,
    safetyScore: 54,
    recommendationReason: 'Shortest geographical path, but traverses dark industrial alleyway with 2 recent harassment reports and broken lighting.',
    factors: {
      lighting: 42,
      footTraffic: 25,
      emergencyProximity: 48,
      incidentDensityScore: 50,
      infrastructureScore: 58,
      isolationRisk: 78,
    },
    keyHighlights: [
      'Saves 8 minutes of walking time',
    ],
    riskWarnings: [
      '⚠️ Low lighting: 4 broken streetlamps',
      '⚠️ High isolation score: No open stores for 500m',
      '⚠️ 2 community safety incident reports within 48h',
    ],
    coordinates: [
      [-122.4225, 37.7805],
      [-122.4198, 37.7770],
      [-122.4160, 37.7730],
      [-122.4128, 37.7738],
    ],
    segments: [
      {
        id: 'seg-7',
        route_id: 'route-fastest',
        segment_index: 0,
        start_lat: 37.7805,
        start_lng: -122.4225,
        end_lat: 37.7770,
        end_lng: -122.4198,
        risk_level: 'medium',
        lighting_score: 60,
        incident_count: 1,
        nearby_amenities_count: 1,
      },
      {
        id: 'seg-8',
        route_id: 'route-fastest',
        segment_index: 1,
        start_lat: 37.7770,
        start_lng: -122.4198,
        end_lat: 37.7730,
        end_lng: -122.4160,
        risk_level: 'high',
        lighting_score: 35,
        incident_count: 2,
        nearby_amenities_count: 0,
        notes: 'Hazard Zone: Poor lighting, low visibility, zero open businesses',
      },
      {
        id: 'seg-9',
        route_id: 'route-fastest',
        segment_index: 2,
        start_lat: 37.7730,
        start_lng: -122.4160,
        end_lat: 37.7738,
        end_lng: -122.4128,
        risk_level: 'low',
        lighting_score: 80,
        incident_count: 0,
        nearby_amenities_count: 2,
      },
    ],
  },
];

export const SEEDED_WALKTOGETHER_COMPANIONS: WalkTogetherRequest[] = [
  {
    id: 'wt-1',
    requester_id: 'companion-maya',
    matched_user_id: 'user-alex-rivera',
    requester_name: 'Maya Lin',
    matched_user_badge: 'Verified University Student 🎓',
    approx_origin_lat: 37.7808,
    approx_origin_lng: -122.4229,
    approx_dest_lat: 37.7740,
    approx_dest_lng: -122.4132,
    approx_distance_meters: 180,
    overlap_percentage: 86,
    status: 'pending',
    created_at: '2026-08-19T10:00:00Z',
    expires_at: '2026-08-19T11:00:00Z',
  },
  {
    id: 'wt-2',
    requester_id: 'companion-kevin',
    matched_user_id: 'user-alex-rivera',
    requester_name: 'Kevin Brooks',
    matched_user_badge: 'Verified Resident (Civic Center) 🛡️',
    approx_origin_lat: 37.7795,
    approx_origin_lng: -122.4201,
    approx_dest_lat: 37.7750,
    approx_dest_lng: -122.4140,
    approx_distance_meters: 320,
    overlap_percentage: 68,
    status: 'pending',
    created_at: '2026-08-19T10:05:00Z',
    expires_at: '2026-08-19T11:05:00Z',
  },
];

export const SEEDED_RECENT_JOURNEYS: SafetyJourney[] = [
  {
    id: 'journey-past-1',
    user_id: 'user-alex-rivera',
    origin_name: 'University Science Quad',
    origin_lat: 37.7820,
    origin_lng: -122.4240,
    dest_name: 'Oak Street Apartments',
    dest_lat: 37.7738,
    dest_lng: -122.4128,
    transport_mode: 'walking',
    route_name: 'Avenue of the Arts',
    safety_score: 94,
    distance_km: 2.3,
    estimated_duration_mins: 26,
    expected_arrival_at: '2026-08-18T22:30:00Z',
    grace_period_seconds: 60,
    status: 'completed',
    started_at: '2026-08-18T22:04:00Z',
    completed_at: '2026-08-18T22:28:15Z',
  },
  {
    id: 'journey-past-2',
    user_id: 'user-alex-rivera',
    origin_name: 'Downtown Public Library',
    origin_lat: 37.7805,
    origin_lng: -122.4225,
    dest_name: 'Oak Street Apartments',
    dest_lat: 37.7738,
    dest_lng: -122.4128,
    transport_mode: 'walking',
    route_name: 'Market St Transit Corridor',
    safety_score: 82,
    distance_km: 1.8,
    estimated_duration_mins: 20,
    expected_arrival_at: '2026-08-17T21:15:00Z',
    grace_period_seconds: 60,
    status: 'completed',
    started_at: '2026-08-17T20:52:00Z',
    completed_at: '2026-08-17T21:12:40Z',
  },
];
